default:
  port: 5299
  database: 'mongodb://localhost/time-machine'
  appServer: 'http://localhost:3000/'
  sessionTtl: 3600 # 60(MINUTE_PER_HOUR) * 60(SECONDS_PER_MINUTE)
  emailServer: 'localhost:3000'
  emailAccount: 'twarss@163.com'
  emailPassword: 'ssww123456'
